### ISSUE TITLE
Additional Verification

### ISSUE THREAD

**Issue by AndyP444** [wmcadigital/wmn-disruption-manage#104]
When you add a new service to get alerts from you don't see it appear in the list, and it sends you another verification email to click. If already in the managed account why do you need to verify subscription again? If I added multiple new routes would I get multiple emails? If so do you then have to click each email to verify or just one? It seems a bit too much of a faf on the customer.

**Comment by KaterinaKir** [comment]
@AndyP444 We also had initial concerns about this extra confirmation step. However, back end insisted that we have this feature for security because at the moment we are not creating password protected accounts so in theory someone can use your email and add multiple services to your email without you knowing and you would start receiving alerts. This confirmation email alerts user if they haven’t signed up for notifications and prevents them from receiving further alerts.
